#!/bin/bash
echo "Copying BTJS3.sh"
cp /media/usb/mbb_update/BTJS3.sh /root/.
echo "Copying BTJS3d"
cp /media/usb/mbb_update/BTJS3d /root/.
echo "Copying btlist.conf"
cp /media/usb/mbb_update/btlist.conf /root/.
echo "Copying btpair"
cp /media/usb/mbb_update/btpair /root/.
echo "Copying btpair.c"
cp /media/usb/mbb_update/btpair.c /root/.
echo "Copying btscan"
cp /media/usb/mbb_update/btscan /root/.
echo "Copying btscan.c"
cp /media/usb/mbb_update/btscan.c /root/.
echo "Copying btslct"
cp /media/usb/mbb_update/btslct /root/.
echo "Copying btslct.c"
cp /media/usb/mbb_update/btslct.c /root/.
echo "Copying btslct.conf"
cp /media/usb/mbb_update/btslct.conf /root/.
echo "Copying btunpair"
cp /media/usb/mbb_update/btunpair /root/.
echo "Copying btunpair.c"
cp /media/usb/mbb_update/btunpair.c /root/.
echo "Copying btunpair2"
cp /media/usb/mbb_update/btunpair2 /root/.
echo "Copying jt3"
cp /media/usb/mbb_update/jt3 /root/.
echo "Copying jtcomp3.sh"
cp /media/usb/mbb_update/jtcomp3.sh /root/.
echo "Copying nxtbtjs2.c"
cp /media/usb/mbb_update/nxtbtjs2.c /root/.
echo "Copying run_js2.sh"
cp /media/usb/mbb_update/run_js2.sh /root/.
echo "Copying test.sh"
cp /media/usb/mbb_update/test.sh /root/.
echo "Copying update.sh"
cp /media/usb/mbb_update/update.sh /root/.
echo "Copying update_chk.sh"
cp /media/usb/mbb_update/update_chk.sh /root/.

